### PR TITLE
`HeaderName::from_static` requires all-lowercase HTTP2 compatible hea…

### PR DESCRIPTION
**Pull request by sdroege**
…der names

and was passed header names with uppercase characters instead, which
made it panic.

### CODE REVIEW

**Comment by sdroege** [comment]
See https://docs.rs/http/latest/http/header/struct.HeaderName.html#method.from_static

**Comment by sdroege** [comment]
Also it's unclear to me why none of the existing tests caught this.

**Comment by sdroege** [comment]
That would be the other option. I can update the PR accordingly, your decision which variant you prefer :)

**Comment by sdroege** [comment]
Well, calling `HeaderName::from_bytes()`.

That's btw called implicitly by the `remove()` and `get()` calls on the strings too and does heap allocations. If that's something you worry about then the list of header names should be stored as actual `HeaderName`s instead of strings statically (e.g. via `once_cell::sync::Lazy`).

**Comment by sdroege** [comment]
Sure, updated accordingly

**Comment by application-developer-DA** [comment]
Thanks! 👍

**Comment by sdroege** [comment]
Can you release a 0.17.2 with this fix in the near future?

**Comment by application-developer-DA** [comment]
Sure! I'll try to publish it today along with the updated `tokio-tungstenite`.

**Comment by sdroege** [comment]
Nice, thanks! I noticed this btw from a user of async-tungstenite. I've released a version of that using tungstenite 0.17 during the weekend.

**Pull request merged**
