### PR TITLE
connect support timeout

### PR DESCRIPTION
**Pull request by errord**
connect support timeout

### CODE REVIEW

**Comment by application-developer-DA** [comment]
Hm, this is ok, but would break the compatibility with the current version. @agalakhov I need your opinion -- would you like to have it like this or should we instead introduce the function with `timeout` parameter parallel to the existing one, so that we stay backwards-compatible?

**Comment by application-developer-DA** [comment]
@agalakhov I'm still thinking that probably doing a separate function for this instead of modifying our existing one would be a better idea, what do you think? Do we want to have this possibility at all? The `TcpStream` has different functions for that, so I think having a separate function (if at all supporting this) would be a better turn.

**Comment by agalakhov** [comment]
Yes, it should be `connect_with_timeout()` or something like that. The ordinary `connect()` function could be a wrapper with infinite timeout.

**Review by application-developer-DA — CHANGES_REQUESTED** [review]
It would be nice to implement changes from https://github.com/snapview/tungstenite-rs/pull/117#issuecomment-669272772 to be able to merge this PR.

If you think that it does not make sense, feel free to use `tokio-tungstenite` as it allows having such flexibility.

**Comment by application-developer-DA** [comment]
It looks like this PR is obsolete and there was no feedback since October, so I'm going to close it. Feel free to open a new one (rebased to master ;)

**Pull request closed without merging**
