### PR TITLE
Remove thiserror dependency

### PR DESCRIPTION
**Pull request by c410-f3r**
Removes two transient dependencies for downstream libraries.

### CODE REVIEW

**Comment by strohel** [comment]
Hi @c410-f3r, thanks for a PR. We've deliberately decided to use thiserror to reduce boilerplate code. But such a decision can be revisited, especially is build time savings would be significant.

Can you please measure build times on your computer, with and without this patch applied? 2 cases, ideally: clean release build `cargo clean; time cargo build --release`; incremental development build: `time cargo build` (drop the first run). Please do multiple runs of each measurement so that we get a sense what the natural variance is. Thanks!

**Comment by c410-f3r** [comment]
Before this PR (1 thread):
```
real    0m27,821s
user    0m24,481s
sys     0m2,461
```

After this PR (1 thread):
```
real    0m20,859s
user    0m18,898s
sys     0m2,019s
```

`cargo build` dependencies went down from `76` to `66`. Don't know why.
It is OK if you guys prefer `thiserror`, my motivation was the addition of more dependencies into downstream libraries. Please, just don't use `anyhow` in the future.

**Comment by agalakhov** [comment]
This looks like reverting the introduction of `thiserror`. Looks like it is the classical "readability vs performance".

**Comment by application-developer-DA** [comment]
> Please, just don't use anyhow in the future.

We don't plan to use `anyhow`. In fact `anyhow` is not meant for libraries as its main purpose is to be used in binary crates. `thiserror` is pretty much the version of `anyhow` for libraries if I'm allowed to generalise it like this.

The difference in build time seems to be negligible (just 10% on my machine, which is around 2,5 second in my particular setup), so I would prefer the version with `thiserror` as it allows to have a cleaner code which is easy to read and maintain.

**Comment by c410-f3r** [comment]
Closed due to the above review

**Pull request closed without merging**
