### PR TITLE
Small clippy fixes

### PR DESCRIPTION
**Pull request by bluetech**
There are still some suggestions left, but they are either bad or would break API (and one for which I'll open a separate issue).

### CODE REVIEW

**Comment by bluetech** [comment]
No problem. Feel free to close or let me know if/when you want me to rebase.

**Comment by agalakhov** [comment]
I just pushed the `devel` branch which contains most of the changes. Feel free to rebase.

**Comment by bluetech** [comment]
Rebased on `devel` branch. I also added a new commit.

**Comment by application-developer-DA** [comment]
@agalakhov I think some of the changes done in this pull request are in conflict with the changes you've recently done in `devel` branch. If your #43 fully covers the changes in this pull request, then we probably have to close it, so that we don't end up merging 2 "almost equal" pull requests.

**Comment by application-developer-DA** [comment]
@agalakhov ok, as there was no action, I've decided to resolve a merge conflict and wait till Travis reports success (compilation + tests) and it seems that the pull request can now safely be merged into the master branch.

Thanks.

**Pull request merged**
